/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trips;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Lenovo
 */
public class Trips extends javax.swing.JFrame {

    /**
     * Creates new form Trips
     */
    
    
    

    
    public Trips() {
        initComponents();
        
        
       
        
        
      
        
        
        
        setTitle("BookyBook"); 

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        bookPanel = new javax.swing.JPanel();
        SearchQ = new javax.swing.JLabel();
        contButton1 = new javax.swing.JButton();
        FlightCheckbox = new javax.swing.JCheckBox();
        HotelCheckbox = new javax.swing.JCheckBox();
        DayToursCheckbox = new javax.swing.JCheckBox();
        Flights = new javax.swing.JLabel();
        Hotels = new javax.swing.JLabel();
        DayTours = new javax.swing.JLabel();
        hotelPanel = new javax.swing.JPanel();
        hotelLabel = new javax.swing.JLabel();
        contButton2 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        hotelsContainer1 = new javax.swing.JLayeredPane();
        arrivalDateLabel = new javax.swing.JLabel();
        arrivalDate = new javax.swing.JTextField();
        nightsLabel = new javax.swing.JLabel();
        nights = new javax.swing.JComboBox();
        locationLabel = new javax.swing.JLabel();
        hotelLocation = new javax.swing.JTextField();
        hotelNameLabel = new javax.swing.JLabel();
        hotelName = new javax.swing.JTextField();
        starsLabel = new javax.swing.JLabel();
        stars = new javax.swing.JComboBox();
        priceLabel = new javax.swing.JLabel();
        maxPrice = new javax.swing.JTextField();
        hotelsContainer2 = new javax.swing.JLayeredPane();
        selectLabel = new javax.swing.JLabel();
        onePers = new javax.swing.JComboBox();
        twoPers = new javax.swing.JComboBox();
        threePers = new javax.swing.JComboBox();
        fourPers = new javax.swing.JComboBox();
        onePersLabel = new javax.swing.JLabel();
        twoPersLabel = new javax.swing.JLabel();
        threePersLabel = new javax.swing.JLabel();
        fourPersLabel = new javax.swing.JLabel();
        hotelSearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HotelsTable = new javax.swing.JTable();
        dayToursPanel = new javax.swing.JPanel();
        dayToursLabel = new javax.swing.JLabel();
        contButton3 = new javax.swing.JButton();
        dayToursContainer1 = new javax.swing.JLayeredPane();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        dayToursContainer2 = new javax.swing.JLayeredPane();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jRadioButton7 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        DayTourSearchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DayToursTable = new javax.swing.JTable();
        flightPanel = new javax.swing.JPanel();
        flightLabel = new javax.swing.JLabel();
        contButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        bookPanel.setBackground(new java.awt.Color(255, 255, 255));

        SearchQ.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        SearchQ.setText("What would you like to search for?");

        contButton1.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        contButton1.setText("Continue");
        contButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButton1ActionPerformed(evt);
            }
        });

        FlightCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightCheckboxActionPerformed(evt);
            }
        });

        HotelCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelCheckboxActionPerformed(evt);
            }
        });

        DayToursCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayToursCheckboxActionPerformed(evt);
            }
        });

        Flights.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        Flights.setText("Flights");

        Hotels.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        Hotels.setText("Hotels");

        DayTours.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        DayTours.setText("Day Tours");

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Flights)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookPanelLayout.createSequentialGroup()
                                .addComponent(FlightCheckbox)
                                .addGap(29, 29, 29)))
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(Hotels))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(HotelCheckbox)))
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(DayTours))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(DayToursCheckbox))))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(contButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(SearchQ)))
                .addContainerGap(864, Short.MAX_VALUE))
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(SearchQ)
                .addGap(56, 56, 56)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Flights, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hotels, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DayTours, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FlightCheckbox)
                        .addComponent(HotelCheckbox))
                    .addComponent(DayToursCheckbox))
                .addGap(69, 69, 69)
                .addComponent(contButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        mainPanel.add(bookPanel, "card12");

        hotelPanel.setBackground(new java.awt.Color(255, 255, 255));

        hotelLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        hotelLabel.setText("Hotels");

        contButton2.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        contButton2.setText("Continue");
        contButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButton2ActionPerformed(evt);
            }
        });

        backButton1.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        backButton1.setText("Back");
        backButton1.setMaximumSize(new java.awt.Dimension(137, 41));
        backButton1.setMinimumSize(new java.awt.Dimension(137, 41));
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        hotelsContainer1.setLayout(new java.awt.GridLayout(0, 2, 10, 15));

        arrivalDateLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        arrivalDateLabel.setText("Arrival date (yyyymmdd)");
        hotelsContainer1.add(arrivalDateLabel);
        hotelsContainer1.add(arrivalDate);

        nightsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        nightsLabel.setText("Number of nights");
        nightsLabel.setToolTipText("");
        hotelsContainer1.add(nightsLabel);

        nights.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", " ", " " }));
        nights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightsActionPerformed(evt);
            }
        });
        hotelsContainer1.add(nights);

        locationLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        locationLabel.setText("Hotel location");
        hotelsContainer1.add(locationLabel);

        hotelLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelLocationActionPerformed(evt);
            }
        });
        hotelsContainer1.add(hotelLocation);

        hotelNameLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelNameLabel.setText("Hotel name");
        hotelsContainer1.add(hotelNameLabel);
        hotelsContainer1.add(hotelName);

        starsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        starsLabel.setText("Minimum stars");
        hotelsContainer1.add(starsLabel);

        stars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "1", "2", "3", "4", "5" }));
        hotelsContainer1.add(stars);

        priceLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        priceLabel.setText("Maximum price");
        priceLabel.setMaximumSize(new java.awt.Dimension(119, 19));
        priceLabel.setMinimumSize(new java.awt.Dimension(119, 19));
        priceLabel.setPreferredSize(new java.awt.Dimension(119, 19));
        hotelsContainer1.add(priceLabel);

        maxPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxPriceActionPerformed(evt);
            }
        });
        hotelsContainer1.add(maxPrice);

        selectLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        selectLabel.setText("Please select the number of rooms of each type you wish to book:");

        onePers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        twoPers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));

        threePers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        fourPers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        onePersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        onePersLabel.setText("1 pers");

        twoPersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        twoPersLabel.setText("2 pers");

        threePersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        threePersLabel.setText("3 pers");

        fourPersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        fourPersLabel.setText("4 pers");

        javax.swing.GroupLayout hotelsContainer2Layout = new javax.swing.GroupLayout(hotelsContainer2);
        hotelsContainer2.setLayout(hotelsContainer2Layout);
        hotelsContainer2Layout.setHorizontalGroup(
            hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelsContainer2Layout.createSequentialGroup()
                .addComponent(selectLabel)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelsContainer2Layout.createSequentialGroup()
                .addComponent(onePersLabel)
                .addGap(18, 18, 18)
                .addComponent(onePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(twoPersLabel)
                .addGap(18, 18, 18)
                .addComponent(threePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(threePersLabel)
                .addGap(18, 18, 18)
                .addComponent(twoPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fourPersLabel)
                .addGap(18, 18, 18)
                .addComponent(fourPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        hotelsContainer2Layout.setVerticalGroup(
            hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelsContainer2Layout.createSequentialGroup()
                .addComponent(selectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onePersLabel)
                    .addComponent(twoPersLabel)
                    .addComponent(threePersLabel)
                    .addComponent(fourPersLabel))
                .addGap(25, 25, 25))
        );
        hotelsContainer2.setLayer(selectLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(onePers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(twoPers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(threePers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(fourPers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(onePersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(twoPersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(threePersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(fourPersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        hotelSearchButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        hotelSearchButton.setText("Search");
        hotelSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelSearchButtonActionPerformed(evt);
            }
        });

        HotelsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Stars", "Price", "PostalCode", "Selected"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HotelsTable);

        javax.swing.GroupLayout hotelPanelLayout = new javax.swing.GroupLayout(hotelPanel);
        hotelPanel.setLayout(hotelPanelLayout);
        hotelPanelLayout.setHorizontalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contButton2)
                .addGap(68, 68, 68))
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(hotelLabel))
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hotelSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hotelsContainer1)
                                .addComponent(hotelsContainer2)))
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(609, Short.MAX_VALUE))
        );
        hotelPanelLayout.setVerticalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelLabel)
                .addGap(40, 40, 40)
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addComponent(hotelsContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hotelsContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(hotelSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        mainPanel.add(hotelPanel, "card11");

        dayToursPanel.setBackground(new java.awt.Color(255, 255, 255));

        dayToursLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        dayToursLabel.setText(" DayTours");

        contButton3.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        contButton3.setText("Continue");

        dayToursContainer1.setLayout(new java.awt.GridLayout(0, 2, 10, 15));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jRadioButton2.setText("Age restriction ( years )");
        jRadioButton2.setMaximumSize(new java.awt.Dimension(83, 27));
        jRadioButton2.setMinimumSize(new java.awt.Dimension(83, 27));
        jRadioButton2.setOpaque(false);
        jRadioButton2.setPreferredSize(new java.awt.Dimension(83, 27));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        dayToursContainer1.add(jRadioButton2);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        dayToursContainer1.add(jTextField2);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jRadioButton3.setText("Location");
        dayToursContainer1.add(jRadioButton3);
        dayToursContainer1.add(jTextField3);

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jRadioButton4.setText("Minimum star rating");
        dayToursContainer1.add(jRadioButton4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        dayToursContainer1.add(jComboBox1);

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jRadioButton5.setText("Departure time ( hh:mm )");
        dayToursContainer1.add(jRadioButton5);
        dayToursContainer1.add(jTextField4);

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jRadioButton6.setText("Number of seats available");
        dayToursContainer1.add(jRadioButton6);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        dayToursContainer1.add(jComboBox2);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jRadioButton1.setText("Price ( ISK )");
        jRadioButton1.setMaximumSize(new java.awt.Dimension(83, 27));
        jRadioButton1.setMinimumSize(new java.awt.Dimension(83, 27));
        jRadioButton1.setOpaque(false);
        jRadioButton1.setPreferredSize(new java.awt.Dimension(83, 27));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel1.setText("-");

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Thu");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Fri");

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Sat");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("Sun");

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Wed");

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jRadioButton7.setText("Days of week");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Mon");

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Tue");

        javax.swing.GroupLayout dayToursContainer2Layout = new javax.swing.GroupLayout(dayToursContainer2);
        dayToursContainer2.setLayout(dayToursContainer2Layout);
        dayToursContainer2Layout.setHorizontalGroup(
            dayToursContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayToursContainer2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jCheckBox1)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox2)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox3)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jCheckBox5)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox6)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox7)
                .addContainerGap())
            .addGroup(dayToursContainer2Layout.createSequentialGroup()
                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dayToursContainer2Layout.setVerticalGroup(
            dayToursContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dayToursContainer2Layout.createSequentialGroup()
                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(dayToursContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addGap(36, 36, 36))
        );
        dayToursContainer2.setLayer(jCheckBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jRadioButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DayTourSearchButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        DayTourSearchButton.setText("Search");
        DayTourSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayTourSearchButtonActionPerformed(evt);
            }
        });

        DayToursTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Price", "Duration", "Description", "Selected"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(DayToursTable);

        javax.swing.GroupLayout dayToursPanelLayout = new javax.swing.GroupLayout(dayToursPanel);
        dayToursPanel.setLayout(dayToursPanelLayout);
        dayToursPanelLayout.setHorizontalGroup(
            dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayToursPanelLayout.createSequentialGroup()
                .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DayTourSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dayToursPanelLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(dayToursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dayToursPanelLayout.createSequentialGroup()
                            .addGap(303, 303, 303)
                            .addComponent(contButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dayToursPanelLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dayToursPanelLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dayToursContainer1)
                                .addComponent(dayToursContainer2)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        dayToursPanelLayout.setVerticalGroup(
            dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayToursPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayToursLabel)
                .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dayToursPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayToursContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayToursContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DayTourSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dayToursPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(contButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        mainPanel.add(dayToursPanel, "card12");

        flightPanel.setBackground(new java.awt.Color(255, 255, 255));

        flightLabel.setText("Flight stuff");

        contButton4.setText("Continue");
        contButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout flightPanelLayout = new javax.swing.GroupLayout(flightPanel);
        flightPanel.setLayout(flightPanelLayout);
        flightPanelLayout.setHorizontalGroup(
            flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightPanelLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addGroup(flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contButton4)
                    .addComponent(flightLabel))
                .addContainerGap(1184, Short.MAX_VALUE))
        );
        flightPanelLayout.setVerticalGroup(
            flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(flightLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(contButton4)
                .addGap(87, 87, 87))
        );

        mainPanel.add(flightPanel, "card10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButton1ActionPerformed
        
        if(FlightCheckbox.isSelected()){
           flightPanel.setVisible(true);
           bookPanel.setVisible(false);
        }
        else if (HotelCheckbox.isSelected()){
            hotelPanel.setVisible(true);
            bookPanel.setVisible(false);
        }
        else if (DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            bookPanel.setVisible(false);
            jRadioButton1.setSelected(true);
            
        }
        
        
        
    }//GEN-LAST:event_contButton1ActionPerformed

    private void DayToursCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayToursCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayToursCheckboxActionPerformed

    private void FlightCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightCheckboxActionPerformed

    private void HotelCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotelCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HotelCheckboxActionPerformed

    private void contButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButton2ActionPerformed
        if (DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            hotelPanel.setVisible(false);
            jRadioButton1.setSelected(true);
        }    
        
        
    }//GEN-LAST:event_contButton2ActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        if(FlightCheckbox.isSelected()){
            flightPanel.setVisible(true);
            hotelPanel.setVisible(false);
            
        }
        
        
    }//GEN-LAST:event_backButton1ActionPerformed

    private void contButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButton4ActionPerformed
        
        if(HotelCheckbox.isSelected()){
            hotelPanel.setVisible(true);
            flightPanel.setVisible(false);
             
        }
         else if (DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            bookPanel.setVisible(false);
            jRadioButton1.setSelected(true);
            
        }
        
    }//GEN-LAST:event_contButton4ActionPerformed

    private void nightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nightsActionPerformed

    private void hotelLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelLocationActionPerformed

    private void maxPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxPriceActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void DayTourSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayTourSearchButtonActionPerformed
     
    }//GEN-LAST:event_DayTourSearchButtonActionPerformed

    private void hotelSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelSearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelSearchButtonActionPerformed


    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DayTourSearchButton;
    private javax.swing.JLabel DayTours;
    private javax.swing.JCheckBox DayToursCheckbox;
    private javax.swing.JTable DayToursTable;
    private javax.swing.JCheckBox FlightCheckbox;
    private javax.swing.JLabel Flights;
    private javax.swing.JCheckBox HotelCheckbox;
    private javax.swing.JLabel Hotels;
    private javax.swing.JTable HotelsTable;
    private javax.swing.JLabel SearchQ;
    private javax.swing.JTextField arrivalDate;
    private javax.swing.JLabel arrivalDateLabel;
    private javax.swing.JButton backButton1;
    private javax.swing.JPanel bookPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton contButton1;
    private javax.swing.JButton contButton2;
    private javax.swing.JButton contButton3;
    private javax.swing.JButton contButton4;
    private javax.swing.JLayeredPane dayToursContainer1;
    private javax.swing.JLayeredPane dayToursContainer2;
    private javax.swing.JLabel dayToursLabel;
    private javax.swing.JPanel dayToursPanel;
    private javax.swing.JLabel flightLabel;
    private javax.swing.JPanel flightPanel;
    private javax.swing.JComboBox fourPers;
    private javax.swing.JLabel fourPersLabel;
    private javax.swing.JLabel hotelLabel;
    private javax.swing.JTextField hotelLocation;
    private javax.swing.JTextField hotelName;
    private javax.swing.JLabel hotelNameLabel;
    private javax.swing.JPanel hotelPanel;
    private javax.swing.JButton hotelSearchButton;
    private javax.swing.JLayeredPane hotelsContainer1;
    private javax.swing.JLayeredPane hotelsContainer2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField maxPrice;
    private javax.swing.JComboBox nights;
    private javax.swing.JLabel nightsLabel;
    private javax.swing.JComboBox onePers;
    private javax.swing.JLabel onePersLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JComboBox stars;
    private javax.swing.JLabel starsLabel;
    private javax.swing.JComboBox threePers;
    private javax.swing.JLabel threePersLabel;
    private javax.swing.JComboBox twoPers;
    private javax.swing.JLabel twoPersLabel;
    // End of variables declaration//GEN-END:variables
}
