/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trips01;

import java.awt.CardLayout;
import java.io.IOException;
import java.text.ParseException;
import java.util.Random;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
	DefaultTableModel model;
    TripLogic logic = new TripLogic();

    
    public Main() {
        initComponents();
        model = (DefaultTableModel) DayToursTable.getModel();
        
        
       
        
        
      
        
        
        
        setTitle("BookyBook"); 

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        bookPanel = new javax.swing.JPanel();
        SearchQ = new javax.swing.JLabel();
        contButton1 = new javax.swing.JButton();
        FlightCheckbox = new javax.swing.JCheckBox();
        HotelCheckbox = new javax.swing.JCheckBox();
        DayToursCheckbox = new javax.swing.JCheckBox();
        Flights = new javax.swing.JLabel();
        Hotels = new javax.swing.JLabel();
        DayTours = new javax.swing.JLabel();
        bookPanelContainer = new javax.swing.JLayeredPane();
        hotelPanel = new javax.swing.JPanel();
        hotelLabel = new javax.swing.JLabel();
        hotelContButton = new javax.swing.JButton();
        hotelBackButton = new javax.swing.JButton();
        hotelsContainer1 = new javax.swing.JLayeredPane();
        arrivalDateLabel = new javax.swing.JLabel();
        arrivalDate = new javax.swing.JTextField();
        nightsLabel = new javax.swing.JLabel();
        nights = new javax.swing.JComboBox();
        locationLabel = new javax.swing.JLabel();
        hotelLocation = new javax.swing.JTextField();
        hotelNameLabel = new javax.swing.JLabel();
        hotelName = new javax.swing.JTextField();
        starsLabel = new javax.swing.JLabel();
        stars = new javax.swing.JComboBox();
        priceLabel = new javax.swing.JLabel();
        maxPrice = new javax.swing.JTextField();
        hotelsContainer2 = new javax.swing.JLayeredPane();
        selectLabel = new javax.swing.JLabel();
        onePers = new javax.swing.JComboBox();
        twoPers = new javax.swing.JComboBox();
        threePers = new javax.swing.JComboBox();
        fourPers = new javax.swing.JComboBox();
        onePersLabel = new javax.swing.JLabel();
        twoPersLabel = new javax.swing.JLabel();
        threePersLabel = new javax.swing.JLabel();
        fourPersLabel = new javax.swing.JLabel();
        hotelSearchButton = new javax.swing.JButton();
        hotelsScrollPane = new javax.swing.JScrollPane();
        HotelsTable = new javax.swing.JTable();
        dayToursPanel = new javax.swing.JPanel();
        dayToursLabel = new javax.swing.JLabel();
        dayToursContButton = new javax.swing.JButton();
        dayToursContainer1 = new javax.swing.JLayeredPane();
        AgeRadioButton = new javax.swing.JRadioButton();
        ageRestriction = new javax.swing.JTextField();
        LocationRadioButton = new javax.swing.JRadioButton();
        dayToursLocation = new javax.swing.JComboBox();
        StarsRadioButton = new javax.swing.JRadioButton();
        minStars = new javax.swing.JComboBox();
        DepartureRadioButton = new javax.swing.JRadioButton();
        dayToursDeparture = new javax.swing.JTextField();
        SeatsRadioButton = new javax.swing.JRadioButton();
        seatsAvailable = new javax.swing.JComboBox();
        PriceRadioButton = new javax.swing.JRadioButton();
        dayToursMinPrice = new javax.swing.JTextField();
        fromTo = new javax.swing.JLabel();
        dayToursMaxPrice = new javax.swing.JTextField();
        dayToursContainer2 = new javax.swing.JLayeredPane();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jRadioButton7 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        DayTourSearchButton = new javax.swing.JButton();
        dayToursScrollPane = new javax.swing.JScrollPane();
        DayToursTable = new javax.swing.JTable();
        dayToursBackButton = new javax.swing.JButton();
        numberOfAdultsLabel = new javax.swing.JLabel();
        numberOfAdults = new javax.swing.JComboBox();
        numberOfChildrenPanel = new javax.swing.JLabel();
        numberOfChildren = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        flightPanel = new javax.swing.JPanel();
        flightLabel = new javax.swing.JLabel();
        contButton4 = new javax.swing.JButton();
        resultsPanel = new javax.swing.JPanel();
        startPageButton = new javax.swing.JButton();
        resultsBackButton = new javax.swing.JButton();
        resultsContainerHotels = new javax.swing.JLayeredPane();
        hotelResultNameLabel = new javax.swing.JLabel();
        hotelResultName = new javax.swing.JTextField();
        hotelResultPostalLabel = new javax.swing.JLabel();
        hotelResultPostal = new javax.swing.JTextField();
        hotelResultStarsLabel = new javax.swing.JLabel();
        hotelResultStars = new javax.swing.JTextField();
        hotelResultDateLabel = new javax.swing.JLabel();
        hotelResultDate = new javax.swing.JTextField();
        hotelResultNumberOfNightsLabel = new javax.swing.JLabel();
        hotelResultNumberOfNights = new javax.swing.JTextField();
        hotelResultNumberOfGuestsLabel = new javax.swing.JLabel();
        hotelResultNumberOfGuests = new javax.swing.JTextField();
        hotelResultNumberOfRoomsLabel = new javax.swing.JLabel();
        hotelResultNumberOfRooms = new javax.swing.JTextField();
        hotelResultPriceLabel = new javax.swing.JLabel();
        hotelResultPrice = new javax.swing.JTextField();
        resultsContainerDayTours = new javax.swing.JLayeredPane();
        dayTourResultNameLabel = new javax.swing.JLabel();
        dayTourResultName = new javax.swing.JTextField();
        dayTourResultLocationLabel = new javax.swing.JLabel();
        dayTourResultLocation = new javax.swing.JTextField();
        dayTourResultDepartureTimeLabel = new javax.swing.JLabel();
        dayTourResultDepartureTime = new javax.swing.JTextField();
        dayTourResultDurationLabel = new javax.swing.JLabel();
        dayTourResultDuration = new javax.swing.JTextField();
        dayTourResultNumberOfSeatsLabel = new javax.swing.JLabel();
        dayTourResultNumberOfSeats = new javax.swing.JTextField();
        dayTourResultPriceLabel = new javax.swing.JLabel();
        dayTourResultPrice = new javax.swing.JTextField();
        tripInfoLabel = new javax.swing.JLabel();
        hotelInfoLabel = new javax.swing.JLabel();
        dayTourInfoLabel = new javax.swing.JLabel();
        bookButton = new javax.swing.JButton();
        bookingNumberPanel = new javax.swing.JPanel();
        bookingNumberLabel = new javax.swing.JLabel();
        bookingNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        bookPanel.setBackground(new java.awt.Color(255, 255, 255));
        bookPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        SearchQ.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        SearchQ.setText("What would you like to search for?");

        contButton1.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        contButton1.setText("Continue");
        contButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButton1ActionPerformed(evt);
            }
        });

        FlightCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightCheckboxActionPerformed(evt);
            }
        });

        HotelCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelCheckboxActionPerformed(evt);
            }
        });

        DayToursCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayToursCheckboxActionPerformed(evt);
            }
        });

        Flights.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        Flights.setText("Flights");

        Hotels.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        Hotels.setText("Hotels");

        DayTours.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        DayTours.setText("Day Tours");

        javax.swing.GroupLayout bookPanelContainerLayout = new javax.swing.GroupLayout(bookPanelContainer);
        bookPanelContainer.setLayout(bookPanelContainerLayout);
        bookPanelContainerLayout.setHorizontalGroup(
            bookPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        bookPanelContainerLayout.setVerticalGroup(
            bookPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Flights)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookPanelLayout.createSequentialGroup()
                                .addComponent(FlightCheckbox)
                                .addGap(29, 29, 29)))
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(Hotels))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(HotelCheckbox)))
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(DayTours))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(DayToursCheckbox))))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(contButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(bookPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(SearchQ)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(SearchQ)
                .addGap(56, 56, 56)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Flights, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hotels, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DayTours, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FlightCheckbox)
                        .addComponent(HotelCheckbox))
                    .addComponent(DayToursCheckbox))
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(contButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(368, Short.MAX_VALUE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(bookPanelContainer)
                        .addContainerGap())))
        );

        mainPanel.add(bookPanel, "card12");

        hotelPanel.setBackground(new java.awt.Color(255, 255, 255));
        hotelPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        hotelLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        hotelLabel.setText("Hotels");

        hotelContButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        hotelContButton.setText("Continue");
        hotelContButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelContButtonActionPerformed(evt);
            }
        });

        hotelBackButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        hotelBackButton.setText("Back");
        hotelBackButton.setMaximumSize(new java.awt.Dimension(137, 41));
        hotelBackButton.setMinimumSize(new java.awt.Dimension(137, 41));
        hotelBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelBackButtonActionPerformed(evt);
            }
        });

        hotelsContainer1.setLayout(new java.awt.GridLayout(0, 2, 10, 15));

        arrivalDateLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        arrivalDateLabel.setText("Arrival date (yyyymmdd)");
        hotelsContainer1.add(arrivalDateLabel);
        hotelsContainer1.add(arrivalDate);

        nightsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        nightsLabel.setText("Number of nights");
        nightsLabel.setToolTipText("");
        hotelsContainer1.add(nightsLabel);

        nights.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" }));
        nights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightsActionPerformed(evt);
            }
        });
        hotelsContainer1.add(nights);

        locationLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        locationLabel.setText("Hotel location");
        hotelsContainer1.add(locationLabel);

        hotelLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelLocationActionPerformed(evt);
            }
        });
        hotelsContainer1.add(hotelLocation);

        hotelNameLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelNameLabel.setText("Hotel name");
        hotelsContainer1.add(hotelNameLabel);
        hotelsContainer1.add(hotelName);

        starsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        starsLabel.setText("Minimum stars");
        hotelsContainer1.add(starsLabel);

        stars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "1", "2", "3", "4", "5" }));
        hotelsContainer1.add(stars);

        priceLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        priceLabel.setText("Maximum price");
        priceLabel.setMaximumSize(new java.awt.Dimension(119, 19));
        priceLabel.setMinimumSize(new java.awt.Dimension(119, 19));
        priceLabel.setPreferredSize(new java.awt.Dimension(119, 19));
        hotelsContainer1.add(priceLabel);

        maxPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxPriceActionPerformed(evt);
            }
        });
        hotelsContainer1.add(maxPrice);

        selectLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        selectLabel.setText("Please select the number of rooms of each type you wish to book:");

        onePers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        twoPers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));

        threePers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        fourPers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        onePersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        onePersLabel.setText("1 pers");

        twoPersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        twoPersLabel.setText("2 pers");

        threePersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        threePersLabel.setText("3 pers");

        fourPersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        fourPersLabel.setText("4 pers");

        javax.swing.GroupLayout hotelsContainer2Layout = new javax.swing.GroupLayout(hotelsContainer2);
        hotelsContainer2.setLayout(hotelsContainer2Layout);
        hotelsContainer2Layout.setHorizontalGroup(
            hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelsContainer2Layout.createSequentialGroup()
                .addComponent(selectLabel)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelsContainer2Layout.createSequentialGroup()
                .addComponent(onePersLabel)
                .addGap(18, 18, 18)
                .addComponent(onePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(twoPersLabel)
                .addGap(18, 18, 18)
                .addComponent(threePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(threePersLabel)
                .addGap(18, 18, 18)
                .addComponent(twoPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fourPersLabel)
                .addGap(18, 18, 18)
                .addComponent(fourPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        hotelsContainer2Layout.setVerticalGroup(
            hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelsContainer2Layout.createSequentialGroup()
                .addComponent(selectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onePersLabel)
                    .addComponent(twoPersLabel)
                    .addComponent(threePersLabel)
                    .addComponent(fourPersLabel))
                .addGap(25, 25, 25))
        );
        hotelsContainer2.setLayer(selectLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(onePers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(twoPers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(threePers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(fourPers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(onePersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(twoPersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(threePersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(fourPersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        hotelSearchButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        hotelSearchButton.setText("Search");
        hotelSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					hotelSearchButtonActionPerformed(evt);
				} catch (NumberFormatException | ParseException | IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        HotelsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Stars", "Price", "PostalCode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hotelsScrollPane.setViewportView(HotelsTable);

        javax.swing.GroupLayout hotelPanelLayout = new javax.swing.GroupLayout(hotelPanel);
        hotelPanel.setLayout(hotelPanelLayout);
        hotelPanelLayout.setHorizontalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(hotelLabel))
                    .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hotelPanelLayout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(hotelBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hotelContButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hotelPanelLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hotelSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hotelsContainer1)
                                    .addComponent(hotelsContainer2)))
                            .addGap(131, 131, 131)
                            .addComponent(hotelsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 113, Short.MAX_VALUE))
        );
        hotelPanelLayout.setVerticalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelLabel)
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(hotelsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hotelBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelContButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(hotelsContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hotelsContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hotelSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        hotelContButton.getAccessibleContext().setAccessibleDescription("");

        mainPanel.add(hotelPanel, "card11");

        dayToursPanel.setBackground(new java.awt.Color(255, 255, 255));
        dayToursPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        dayToursLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        dayToursLabel.setText(" DayTours");

        dayToursContButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        dayToursContButton.setText("Continue");
        dayToursContButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayToursContButtonActionPerformed(evt);
            }
        });

        dayToursContainer1.setLayout(new java.awt.GridLayout(0, 2, 10, 15));

        AgeRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(AgeRadioButton);
        AgeRadioButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        AgeRadioButton.setText("Age restriction ( years )");
        AgeRadioButton.setMaximumSize(new java.awt.Dimension(83, 27));
        AgeRadioButton.setMinimumSize(new java.awt.Dimension(83, 27));
        AgeRadioButton.setOpaque(false);
        AgeRadioButton.setPreferredSize(new java.awt.Dimension(83, 27));
        AgeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeRadioButtonActionPerformed(evt);
            }
        });
        dayToursContainer1.add(AgeRadioButton);

        ageRestriction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageRestrictionActionPerformed(evt);
            }
        });
        dayToursContainer1.add(ageRestriction);

        LocationRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LocationRadioButton);
        LocationRadioButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        LocationRadioButton.setText("Location");
        dayToursContainer1.add(LocationRadioButton);

        dayToursLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "N", "E", "W", "NE", "NW", "SE", "SW" }));
        dayToursContainer1.add(dayToursLocation);

        StarsRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(StarsRadioButton);
        StarsRadioButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        StarsRadioButton.setText("Minimum star rating");
        dayToursContainer1.add(StarsRadioButton);

        minStars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        dayToursContainer1.add(minStars);

        DepartureRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(DepartureRadioButton);
        DepartureRadioButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        DepartureRadioButton.setText("Departure time ( hh:mm )");
        dayToursContainer1.add(DepartureRadioButton);
        dayToursContainer1.add(dayToursDeparture);

        SeatsRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(SeatsRadioButton);
        SeatsRadioButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        SeatsRadioButton.setText("Number of seats available");
        dayToursContainer1.add(SeatsRadioButton);

        seatsAvailable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        dayToursContainer1.add(seatsAvailable);

        PriceRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(PriceRadioButton);
        PriceRadioButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        PriceRadioButton.setText("Price ( ISK )");
        PriceRadioButton.setMaximumSize(new java.awt.Dimension(83, 27));
        PriceRadioButton.setMinimumSize(new java.awt.Dimension(83, 27));
        PriceRadioButton.setOpaque(false);
        PriceRadioButton.setPreferredSize(new java.awt.Dimension(83, 27));
        PriceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceRadioButtonActionPerformed(evt);
            }
        });

        fromTo.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        fromTo.setText("-");

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Thu");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Fri");

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Sat");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("Sun");

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Wed");

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jRadioButton7.setText("Days of week");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Mon");

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Tue");

        javax.swing.GroupLayout dayToursContainer2Layout = new javax.swing.GroupLayout(dayToursContainer2);
        dayToursContainer2.setLayout(dayToursContainer2Layout);
        dayToursContainer2Layout.setHorizontalGroup(
            dayToursContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayToursContainer2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jCheckBox1)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox2)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox3)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jCheckBox5)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox6)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox7)
                .addContainerGap())
            .addGroup(dayToursContainer2Layout.createSequentialGroup()
                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dayToursContainer2Layout.setVerticalGroup(
            dayToursContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dayToursContainer2Layout.createSequentialGroup()
                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(dayToursContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addGap(36, 36, 36))
        );
        dayToursContainer2.setLayer(jCheckBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jRadioButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dayToursContainer2.setLayer(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DayTourSearchButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        DayTourSearchButton.setText("Search");
        DayTourSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayTourSearchButtonActionPerformed(evt);
            }
        });

        DayToursTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Duration", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dayToursScrollPane.setViewportView(DayToursTable);

        dayToursBackButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        dayToursBackButton.setText("Back");
        dayToursBackButton.setMaximumSize(new java.awt.Dimension(137, 41));
        dayToursBackButton.setMinimumSize(new java.awt.Dimension(137, 41));
        dayToursBackButton.setPreferredSize(new java.awt.Dimension(137, 41));
        dayToursBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayToursBackButtonActionPerformed(evt);
            }
        });

        numberOfAdultsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        numberOfAdultsLabel.setText("Number of adults");

        numberOfAdults.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        numberOfAdults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfAdultsActionPerformed(evt);
            }
        });

        numberOfChildrenPanel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        numberOfChildrenPanel.setText("Number of children");

        numberOfChildren.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel3.setText("Search by:");

        javax.swing.GroupLayout dayToursPanelLayout = new javax.swing.GroupLayout(dayToursPanel);
        dayToursPanel.setLayout(dayToursPanelLayout);
        dayToursPanelLayout.setHorizontalGroup(
            dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dayToursPanelLayout.createSequentialGroup()
                .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dayToursPanelLayout.createSequentialGroup()
                        .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DayTourSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dayToursPanelLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(dayToursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dayToursPanelLayout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dayToursContainer1)
                                        .addComponent(dayToursContainer2)))
                                .addGroup(dayToursPanelLayout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dayToursPanelLayout.createSequentialGroup()
                                            .addComponent(PriceRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(dayToursMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fromTo, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dayToursMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(dayToursPanelLayout.createSequentialGroup()
                                                .addComponent(numberOfChildrenPanel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(numberOfChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(dayToursPanelLayout.createSequentialGroup()
                                                .addComponent(numberOfAdultsLabel)
                                                .addGap(47, 47, 47)
                                                .addComponent(numberOfAdults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(dayToursScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dayToursPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(dayToursBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dayToursContButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        dayToursPanelLayout.setVerticalGroup(
            dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayToursPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayToursLabel)
                .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dayToursPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfAdultsLabel)
                            .addComponent(numberOfAdults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfChildrenPanel)
                            .addComponent(numberOfChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriceRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayToursMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromTo)
                            .addComponent(dayToursMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayToursContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayToursContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DayTourSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dayToursPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(dayToursScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayToursContButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayToursBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        mainPanel.add(dayToursPanel, "card12");

        flightPanel.setBackground(new java.awt.Color(255, 255, 255));
        flightPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        flightLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        flightLabel.setText("Flights are currently unavailable :(");

        contButton4.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        contButton4.setText("Continue");
        contButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout flightPanelLayout = new javax.swing.GroupLayout(flightPanel);
        flightPanel.setLayout(flightPanelLayout);
        flightPanelLayout.setHorizontalGroup(
            flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightPanelLayout.createSequentialGroup()
                .addGroup(flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(flightPanelLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(flightLabel))
                    .addGroup(flightPanelLayout.createSequentialGroup()
                        .addGap(727, 727, 727)
                        .addComponent(contButton4)))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        flightPanelLayout.setVerticalGroup(
            flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightPanelLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(flightLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(contButton4)
                .addGap(87, 87, 87))
        );

        mainPanel.add(flightPanel, "card10");

        resultsPanel.setBackground(new java.awt.Color(255, 255, 255));
        resultsPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        startPageButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        startPageButton.setText("Restart process");
        startPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPageButtonActionPerformed(evt);
            }
        });

        resultsBackButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        resultsBackButton.setText("Back");
        resultsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsBackButtonActionPerformed(evt);
            }
        });

        resultsContainerHotels.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        hotelResultNameLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelResultNameLabel.setText("Name");
        resultsContainerHotels.add(hotelResultNameLabel);

        hotelResultName.setEditable(false);
        hotelResultName.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        hotelResultName.setFocusable(false);
        resultsContainerHotels.add(hotelResultName);

        hotelResultPostalLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelResultPostalLabel.setText("Postal code");
        resultsContainerHotels.add(hotelResultPostalLabel);

        hotelResultPostal.setEditable(false);
        hotelResultPostal.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        hotelResultPostal.setFocusable(false);
        resultsContainerHotels.add(hotelResultPostal);

        hotelResultStarsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelResultStarsLabel.setText("Stars");
        resultsContainerHotels.add(hotelResultStarsLabel);

        hotelResultStars.setEditable(false);
        hotelResultStars.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        hotelResultStars.setFocusable(false);
        hotelResultStars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelResultStarsActionPerformed(evt);
            }
        });
        resultsContainerHotels.add(hotelResultStars);

        hotelResultDateLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelResultDateLabel.setText("Arrival date");
        resultsContainerHotels.add(hotelResultDateLabel);

        hotelResultDate.setEditable(false);
        hotelResultDate.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        hotelResultDate.setFocusable(false);
        resultsContainerHotels.add(hotelResultDate);

        hotelResultNumberOfNightsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelResultNumberOfNightsLabel.setText("Number of nights");
        resultsContainerHotels.add(hotelResultNumberOfNightsLabel);

        hotelResultNumberOfNights.setEditable(false);
        hotelResultNumberOfNights.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        hotelResultNumberOfNights.setFocusable(false);
        hotelResultNumberOfNights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelResultNumberOfNightsActionPerformed(evt);
            }
        });
        resultsContainerHotels.add(hotelResultNumberOfNights);

        hotelResultNumberOfGuestsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelResultNumberOfGuestsLabel.setText("Number of guests");
        resultsContainerHotels.add(hotelResultNumberOfGuestsLabel);

        hotelResultNumberOfGuests.setEditable(false);
        hotelResultNumberOfGuests.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        hotelResultNumberOfGuests.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hotelResultNumberOfGuests.setFocusable(false);
        resultsContainerHotels.add(hotelResultNumberOfGuests);

        hotelResultNumberOfRoomsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelResultNumberOfRoomsLabel.setText("Number of rooms");
        resultsContainerHotels.add(hotelResultNumberOfRoomsLabel);

        hotelResultNumberOfRooms.setEditable(false);
        hotelResultNumberOfRooms.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        hotelResultNumberOfRooms.setFocusable(false);
        resultsContainerHotels.add(hotelResultNumberOfRooms);

        hotelResultPriceLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelResultPriceLabel.setText("Total price ( EUR )");
        resultsContainerHotels.add(hotelResultPriceLabel);

        hotelResultPrice.setEditable(false);
        hotelResultPrice.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        hotelResultPrice.setFocusable(false);
        resultsContainerHotels.add(hotelResultPrice);

        resultsContainerDayTours.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        dayTourResultNameLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        dayTourResultNameLabel.setText("Name");
        resultsContainerDayTours.add(dayTourResultNameLabel);

        dayTourResultName.setEditable(false);
        dayTourResultName.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        dayTourResultName.setFocusable(false);
        resultsContainerDayTours.add(dayTourResultName);

        dayTourResultLocationLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        dayTourResultLocationLabel.setText("Location");
        resultsContainerDayTours.add(dayTourResultLocationLabel);

        dayTourResultLocation.setEditable(false);
        dayTourResultLocation.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        dayTourResultLocation.setFocusable(false);
        dayTourResultLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTourResultLocationActionPerformed(evt);
            }
        });
        resultsContainerDayTours.add(dayTourResultLocation);

        dayTourResultDepartureTimeLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        dayTourResultDepartureTimeLabel.setText("Departure time");
        resultsContainerDayTours.add(dayTourResultDepartureTimeLabel);

        dayTourResultDepartureTime.setEditable(false);
        dayTourResultDepartureTime.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        dayTourResultDepartureTime.setFocusable(false);
        resultsContainerDayTours.add(dayTourResultDepartureTime);

        dayTourResultDurationLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        dayTourResultDurationLabel.setText("Duration");
        resultsContainerDayTours.add(dayTourResultDurationLabel);

        dayTourResultDuration.setEditable(false);
        dayTourResultDuration.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        dayTourResultDuration.setFocusable(false);
        resultsContainerDayTours.add(dayTourResultDuration);

        dayTourResultNumberOfSeatsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        dayTourResultNumberOfSeatsLabel.setText("Number of seats");
        resultsContainerDayTours.add(dayTourResultNumberOfSeatsLabel);

        dayTourResultNumberOfSeats.setEditable(false);
        dayTourResultNumberOfSeats.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        dayTourResultNumberOfSeats.setFocusable(false);
        resultsContainerDayTours.add(dayTourResultNumberOfSeats);

        dayTourResultPriceLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        dayTourResultPriceLabel.setText("Total price (ISK)");
        resultsContainerDayTours.add(dayTourResultPriceLabel);

        dayTourResultPrice.setEditable(false);
        dayTourResultPrice.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        dayTourResultPrice.setFocusable(false);
        resultsContainerDayTours.add(dayTourResultPrice);

        tripInfoLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        tripInfoLabel.setText("Your Trip Information");

        hotelInfoLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        hotelInfoLabel.setText("Hotel information");

        dayTourInfoLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        dayTourInfoLabel.setText("Daytour information");

        bookButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        bookButton.setText("Book trip");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					bookButtonActionPerformed(evt);
				} catch (ParseException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultsPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(resultsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startPageButton)
                .addGap(20, 20, 20))
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(hotelInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dayTourInfoLabel)
                .addGap(276, 276, 276))
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(tripInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(resultsContainerHotels, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(resultsContainerDayTours, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(bookButton)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tripInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addComponent(hotelInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultsContainerHotels, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultsContainerDayTours, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addComponent(dayTourInfoLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        resultsBackButton.getAccessibleContext().setAccessibleName("resultsBackButton");

        mainPanel.add(resultsPanel, "card6");

        bookingNumberPanel.setBackground(new java.awt.Color(255, 255, 255));
        bookingNumberPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        bookingNumberLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        bookingNumberLabel.setText("Your booking number");

        bookingNumber.setFont(new java.awt.Font("Microsoft YaHei", 0, 48)); // NOI18N
        bookingNumber.setEditable(false);

        javax.swing.GroupLayout bookingNumberPanelLayout = new javax.swing.GroupLayout(bookingNumberPanel);
        bookingNumberPanel.setLayout(bookingNumberPanelLayout);
        bookingNumberPanelLayout.setHorizontalGroup(
            bookingNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingNumberPanelLayout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(bookingNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingNumberPanelLayout.createSequentialGroup()
                        .addComponent(bookingNumberLabel)
                        .addGap(423, 423, 423))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingNumberPanelLayout.createSequentialGroup()
                        .addComponent(bookingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306))))
        );
        bookingNumberPanelLayout.setVerticalGroup(
            bookingNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingNumberPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(bookingNumberLabel)
                .addGap(18, 18, 18)
                .addComponent(bookingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        mainPanel.add(bookingNumberPanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButton1ActionPerformed
        
        if(FlightCheckbox.isSelected()){
           flightPanel.setVisible(true);
           bookPanel.setVisible(false);
        }
        else if (HotelCheckbox.isSelected()){
            hotelPanel.setVisible(true);
            bookPanel.setVisible(false);
        }
        else if (DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            bookPanel.setVisible(false);
            PriceRadioButton.setSelected(true);
            
        }
        
        
        
    }//GEN-LAST:event_contButton1ActionPerformed

    private void DayToursCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayToursCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayToursCheckboxActionPerformed

    private void FlightCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightCheckboxActionPerformed

    private void HotelCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotelCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HotelCheckboxActionPerformed

    private void hotelContButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelContButtonActionPerformed
        if (DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            hotelPanel.setVisible(false);
            PriceRadioButton.setSelected(true);
        } 
        else {
        	resultsPanel.setVisible(true);
        	hotelPanel.setVisible(false);
        }System.out.println(HotelsTable.getSelectedRow());
        int i = HotelsTable.getSelectedRow();
        hotelResultName.setText(logic.GetHotelData().getHotels()[i].getName());
        hotelResultPostal.setText(logic.GetHotelData().getHotels()[i].getPostalCode());
        hotelResultStars.setText(Integer.toString(logic.GetHotelData().getHotels()[i].getStars()));
        hotelResultDate.setText(arrivalDate.getText());
        hotelResultNumberOfNights.setText(Integer.toString(nights.getSelectedIndex()));
        hotelResultNumberOfRooms.setText(Integer.toString(onePers.getSelectedIndex() + twoPers.getSelectedIndex() + threePers.getSelectedIndex() + fourPers.getSelectedIndex()));
        hotelResultPrice.setText(Integer.toString(logic.GetHotelData().getHotels()[i].getPrice()));
        hotelResultNumberOfGuests.setText(Integer.toString(onePers.getSelectedIndex() + 2*twoPers.getSelectedIndex() + 3*threePers.getSelectedIndex() + 4*fourPers.getSelectedIndex()));
        
    }//GEN-LAST:event_hotelContButtonActionPerformed

    private void hotelBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelBackButtonActionPerformed
        if(FlightCheckbox.isSelected()){
            flightPanel.setVisible(true);
            hotelPanel.setVisible(false);
            
        }
        
        
    }//GEN-LAST:event_hotelBackButtonActionPerformed

    private void contButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButton4ActionPerformed
        
        if(HotelCheckbox.isSelected()){
            hotelPanel.setVisible(true);
            flightPanel.setVisible(false);
             
        }
         else if (DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            bookPanel.setVisible(false);
            PriceRadioButton.setSelected(true);
            
        }
        
    }//GEN-LAST:event_contButton4ActionPerformed

    private void nightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nightsActionPerformed

    private void maxPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxPriceActionPerformed

    private void ageRestrictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageRestrictionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageRestrictionActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void AgeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeRadioButtonActionPerformed

    private void PriceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceRadioButtonActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed
    

    
    private DefaultTableModel reset(){
        
        if(model!=null){
            try{
                int radir = model.getRowCount();
                for(int i = radir-1; i >= 0; i--){
                    model.removeRow(i);
                }
            }catch (Exception ex) {
            }
        }
        return model;
    }
    
    
    
    private void DayTourSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayTourSearchButtonActionPerformed
    	boolean[] check = new boolean[7];
    	reset();
    	
    	System.out.println(dayToursMinPrice.getText().isEmpty());
    	if (PriceRadioButton.isSelected()) {
    		if(dayToursMinPrice.getText().isEmpty()){
    			logic.GetDayToursData().setMinPrice(0);
    		}
    		else {
    			logic.GetDayToursData().setMinPrice(Integer.parseInt(dayToursMinPrice.getText()));
    		}
    		if(dayToursMaxPrice.getText().isEmpty()) {
    			logic.GetDayToursData().setMaxPrice(1000000);
    		}
    		else {
    			logic.GetDayToursData().setMaxPrice(Integer.parseInt(dayToursMaxPrice.getText()));
    		}
    		logic.GetDayToursData().setSearchBy(0);
    		logic.DayTourSearch();
    	}
    	if (AgeRadioButton.isSelected()) {
    		if (ageRestriction.getText().isEmpty()) {
    			logic.GetDayToursData().setAgeRestriction(100);
    		}
    		else {
    			logic.GetDayToursData().setAgeRestriction(Integer.parseInt(ageRestriction.getText()));
    		}
    		logic.GetDayToursData().setSearchBy(1);
    		logic.DayTourSearch();
    	}
    	if (LocationRadioButton.isSelected()) {
    			logic.GetDayToursData().setLocation(dayToursLocation.getSelectedItem().toString());
    		logic.GetDayToursData().setSearchBy(2);
    		logic.DayTourSearch();
    	}
    	if (StarsRadioButton.isSelected()) {
    		logic.GetDayToursData().setStars(minStars.getSelectedIndex());
    		logic.GetDayToursData().setSearchBy(3);
    		logic.DayTourSearch();
    	}
    	if (DepartureRadioButton.isSelected()) {
    		if (dayToursDeparture.getText().isEmpty()) {
    			logic.GetDayToursData().setDepartureTime("18:30");
    		}
    		else {
    			logic.GetDayToursData().setDepartureTime(dayToursDeparture.getText());
    		}
    		
    		logic.GetDayToursData().setSearchBy(4);
    		logic.DayTourSearch();
    	}
    	if (SeatsRadioButton.isSelected()) {
    		logic.GetDayToursData().setSeatsAvailable(seatsAvailable.getSelectedIndex());
    		logic.GetDayToursData().setSearchBy(5);
    		logic.DayTourSearch();
    	}
    	if (jRadioButton7.isSelected()) {
    		check[0] = jCheckBox1.isSelected();
    		check[1] = jCheckBox2.isSelected();
    		check[2] = jCheckBox3.isSelected();
    		check[3] = jCheckBox4.isSelected();
    		check[4] = jCheckBox5.isSelected();
    		check[5] = jCheckBox6.isSelected();
    		check[6] = jCheckBox7.isSelected();
    		logic.GetDayToursData().setDaysOfWeek(check);
    		logic.GetDayToursData().setSearchBy(6);
    		logic.DayTourSearch();
    	}
    	for(int i=0; i<25; i++) {
    		if(i < logic.GetDayToursData().getTours().length) {
    			String name = logic.GetDayToursData().getTours()[i].getName();
    			String price = Integer.toString(logic.GetDayToursData().getTours()[i].getPrice());
    			String duration = logic.GetDayToursData().getTours()[i].getDuration();
    			String description = logic.GetDayToursData().getTours()[i].getDescription();
    			String[] rowData = new String[4];
    			rowData[0] = name;
    			rowData[1] = price;
    			rowData[2] = duration;
    			rowData[3] = description;
    			model.addRow(rowData);
    		}
    	}
    }//GEN-LAST:event_DayTourSearchButtonActionPerformed

    private void hotelSearchButtonActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, ParseException, IOException {//GEN-FIRST:event_hotelSearchButtonActionPerformed
    	int[] arr = new int[4];
    	arr[0] = onePers.getSelectedIndex();
    	arr[1] = twoPers.getSelectedIndex();
    	arr[2] = threePers.getSelectedIndex();
    	arr[3] = fourPers.getSelectedIndex();
    	if (maxPrice.getText().isEmpty()) {
    		maxPrice.setText("-1");
    	}
    	logic.HotelSearch(hotelLocation.getText(), arrivalDate.getText(), hotelName.getText(), nights.getSelectedIndex(), stars.getSelectedIndex(), Integer.parseInt(maxPrice.getText()), arr);
    	for(int i=0; i < 25; i++) {
    		if(i < logic.GetHotelData().getHotels().length) {
    			HotelsTable.setValueAt(logic.GetHotelData().getHotels()[i].getName(), i, 0);
    			HotelsTable.setValueAt(logic.GetHotelData().getHotels()[i].getStars(), i, 1);
    			HotelsTable.setValueAt(logic.GetHotelData().getHotels()[i].getPrice(), i, 2);
    			HotelsTable.setValueAt(logic.GetHotelData().getHotels()[i].getPostalCode(), i, 3);
    		}
    	}
    }//GEN-LAST:event_hotelSearchButtonActionPerformed

    private void dayToursContButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayToursContButtonActionPerformed
        resultsPanel.setVisible(true);
        dayToursPanel.setVisible(false);
        int i = DayToursTable.getSelectedRow();
        dayTourResultName.setText(logic.GetDayToursData().getTours()[i].getName());
        dayTourResultLocation.setText(logic.GetDayToursData().getTours()[i].getLocation());
        dayTourResultDepartureTime.setText(logic.GetDayToursData().getTours()[i].getDepartureTime());
        dayTourResultDuration.setText(logic.GetDayToursData().getTours()[i].getDuration());
        dayTourResultNumberOfSeats.setText(Integer.toString(numberOfAdults.getSelectedIndex() + numberOfChildren.getSelectedIndex()));
        dayTourResultName.setText(logic.GetDayToursData().getTours()[i].getName());
        dayTourResultPrice.setText(Integer.toString(logic.GetDayToursData().getTours()[i].getPrice()));
        
    }//GEN-LAST:event_dayToursContButtonActionPerformed

	public static String getBookingId() {
  		StringBuilder randomString = new StringBuilder();
  		Random random = new Random();

		String alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
		for(int i = 0; i < 6; i++) {
			randomString.append(alphabet.charAt(random.nextInt(alphabet.length())));
		}

		return randomString.toString();
	}
    
    
    private void dayToursBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayToursBackButtonActionPerformed
        
         if(HotelCheckbox.isSelected()){
            hotelPanel.setVisible(true);
            dayToursPanel.setVisible(false);
             
        }
         else if (FlightCheckbox.isSelected()){
            flightPanel.setVisible(true);
            dayToursPanel.setVisible(false);
            
            
        }
        
    }//GEN-LAST:event_dayToursBackButtonActionPerformed

    private void hotelLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelLocationActionPerformed

    private void resultsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsBackButtonActionPerformed

        if(DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            resultsPanel.setVisible(false);

        }
        else if(HotelCheckbox.isSelected()){
            hotelPanel.setVisible(true);
            resultsPanel.setVisible(false);

        }
        else if(FlightCheckbox.isSelected()){
            flightPanel.setVisible(true);
            resultsPanel.setVisible(false);
        }
    }//GEN-LAST:event_resultsBackButtonActionPerformed

    private void startPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPageButtonActionPerformed

        bookPanel.setVisible(true);
        resultsPanel.setVisible(false);

    }//GEN-LAST:event_startPageButtonActionPerformed

    private void hotelResultStarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelResultStarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelResultStarsActionPerformed

    private void hotelResultNumberOfNightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelResultNumberOfNightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelResultNumberOfNightsActionPerformed

    private void dayTourResultLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTourResultLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTourResultLocationActionPerformed

    private void numberOfAdultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfAdultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfAdultsActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {//GEN-FIRST:event_bookButtonActionPerformed
        String bookNumber = getBookingId();
        int i = HotelsTable.getSelectedRow();
        int j = DayToursTable.getSelectedRow();
        bookingNumber.setText(bookNumber);
    	if(HotelCheckbox.isSelected()) {
    		logic.BookHotel(bookNumber, i);
    	}
    	if(DayToursCheckbox.isSelected()) {
    		logic.BookDayTour(numberOfAdults.getSelectedIndex(), numberOfChildren.getSelectedIndex(), bookNumber, j);
    	}
    	resultsPanel.setVisible(false);
        bookingNumberPanel.setVisible(true);
    }//GEN-LAST:event_bookButtonActionPerformed


    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AgeRadioButton;
    private javax.swing.JButton DayTourSearchButton;
    private javax.swing.JLabel DayTours;
    private javax.swing.JCheckBox DayToursCheckbox;
    private javax.swing.JTable DayToursTable;
    private javax.swing.JRadioButton DepartureRadioButton;
    private javax.swing.JCheckBox FlightCheckbox;
    private javax.swing.JLabel Flights;
    private javax.swing.JCheckBox HotelCheckbox;
    private javax.swing.JLabel Hotels;
    private javax.swing.JTable HotelsTable;
    private javax.swing.JRadioButton LocationRadioButton;
    private javax.swing.JRadioButton PriceRadioButton;
    private javax.swing.JLabel SearchQ;
    private javax.swing.JRadioButton SeatsRadioButton;
    private javax.swing.JRadioButton StarsRadioButton;
    private javax.swing.JTextField ageRestriction;
    private javax.swing.JTextField arrivalDate;
    private javax.swing.JLabel arrivalDateLabel;
    private javax.swing.JButton bookButton;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JLayeredPane bookPanelContainer;
    private javax.swing.JTextField bookingNumber;
    private javax.swing.JLabel bookingNumberLabel;
    private javax.swing.JPanel bookingNumberPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton contButton1;
    private javax.swing.JButton contButton4;
    private javax.swing.JLabel dayTourInfoLabel;
    private javax.swing.JTextField dayTourResultDepartureTime;
    private javax.swing.JLabel dayTourResultDepartureTimeLabel;
    private javax.swing.JTextField dayTourResultDuration;
    private javax.swing.JLabel dayTourResultDurationLabel;
    private javax.swing.JTextField dayTourResultLocation;
    private javax.swing.JLabel dayTourResultLocationLabel;
    private javax.swing.JTextField dayTourResultName;
    private javax.swing.JLabel dayTourResultNameLabel;
    private javax.swing.JTextField dayTourResultNumberOfSeats;
    private javax.swing.JLabel dayTourResultNumberOfSeatsLabel;
    private javax.swing.JTextField dayTourResultPrice;
    private javax.swing.JLabel dayTourResultPriceLabel;
    private javax.swing.JButton dayToursBackButton;
    private javax.swing.JButton dayToursContButton;
    private javax.swing.JLayeredPane dayToursContainer1;
    private javax.swing.JLayeredPane dayToursContainer2;
    private javax.swing.JTextField dayToursDeparture;
    private javax.swing.JLabel dayToursLabel;
    private javax.swing.JComboBox dayToursLocation;
    private javax.swing.JTextField dayToursMaxPrice;
    private javax.swing.JTextField dayToursMinPrice;
    private javax.swing.JPanel dayToursPanel;
    private javax.swing.JScrollPane dayToursScrollPane;
    private javax.swing.JLabel flightLabel;
    private javax.swing.JPanel flightPanel;
    private javax.swing.JComboBox fourPers;
    private javax.swing.JLabel fourPersLabel;
    private javax.swing.JLabel fromTo;
    private javax.swing.JButton hotelBackButton;
    private javax.swing.JButton hotelContButton;
    private javax.swing.JLabel hotelInfoLabel;
    private javax.swing.JLabel hotelLabel;
    private javax.swing.JTextField hotelLocation;
    private javax.swing.JTextField hotelName;
    private javax.swing.JLabel hotelNameLabel;
    private javax.swing.JPanel hotelPanel;
    private javax.swing.JTextField hotelResultDate;
    private javax.swing.JLabel hotelResultDateLabel;
    private javax.swing.JTextField hotelResultName;
    private javax.swing.JLabel hotelResultNameLabel;
    private javax.swing.JTextField hotelResultNumberOfGuests;
    private javax.swing.JLabel hotelResultNumberOfGuestsLabel;
    private javax.swing.JTextField hotelResultNumberOfNights;
    private javax.swing.JLabel hotelResultNumberOfNightsLabel;
    private javax.swing.JTextField hotelResultNumberOfRooms;
    private javax.swing.JLabel hotelResultNumberOfRoomsLabel;
    private javax.swing.JTextField hotelResultPostal;
    private javax.swing.JLabel hotelResultPostalLabel;
    private javax.swing.JTextField hotelResultPrice;
    private javax.swing.JLabel hotelResultPriceLabel;
    private javax.swing.JTextField hotelResultStars;
    private javax.swing.JLabel hotelResultStarsLabel;
    private javax.swing.JButton hotelSearchButton;
    private javax.swing.JLayeredPane hotelsContainer1;
    private javax.swing.JLayeredPane hotelsContainer2;
    private javax.swing.JScrollPane hotelsScrollPane;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField maxPrice;
    private javax.swing.JComboBox minStars;
    private javax.swing.JComboBox nights;
    private javax.swing.JLabel nightsLabel;
    private javax.swing.JComboBox numberOfAdults;
    private javax.swing.JLabel numberOfAdultsLabel;
    private javax.swing.JComboBox numberOfChildren;
    private javax.swing.JLabel numberOfChildrenPanel;
    private javax.swing.JComboBox onePers;
    private javax.swing.JLabel onePersLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton resultsBackButton;
    private javax.swing.JLayeredPane resultsContainerDayTours;
    private javax.swing.JLayeredPane resultsContainerHotels;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JComboBox seatsAvailable;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JComboBox stars;
    private javax.swing.JLabel starsLabel;
    private javax.swing.JButton startPageButton;
    private javax.swing.JComboBox threePers;
    private javax.swing.JLabel threePersLabel;
    private javax.swing.JLabel tripInfoLabel;
    private javax.swing.JComboBox twoPers;
    private javax.swing.JLabel twoPersLabel;
    // End of variables declaration//GEN-END:variables
}
