/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trips01;

import java.awt.CardLayout;
import java.io.IOException;
import java.text.ParseException;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Lenovo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
	TripLogic logic = new TripLogic();
	
    public Main() {
        initComponents();
        
        
       
        
        
      
        
        
        
        setTitle("BookyBook"); 

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        bookPanel = new javax.swing.JPanel();
        SearchQ = new javax.swing.JLabel();
        contButton1 = new javax.swing.JButton();
        FlightCheckbox = new javax.swing.JCheckBox();
        HotelCheckbox = new javax.swing.JCheckBox();
        DayToursCheckbox = new javax.swing.JCheckBox();
        Flights = new javax.swing.JLabel();
        Hotels = new javax.swing.JLabel();
        DayTours = new javax.swing.JLabel();
        hotelPanel = new javax.swing.JPanel();
        hotelLabel = new javax.swing.JLabel();
        contButton2 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        hotelsContainer1 = new javax.swing.JLayeredPane();
        arrivalDateLabel = new javax.swing.JLabel();
        arrivalDate = new javax.swing.JTextField();
        nightsLabel = new javax.swing.JLabel();
        nights = new javax.swing.JComboBox();
        locationLabel = new javax.swing.JLabel();
        hotelLocation = new javax.swing.JTextField();
        hotelNameLabel = new javax.swing.JLabel();
        hotelName = new javax.swing.JTextField();
        starsLabel = new javax.swing.JLabel();
        stars = new javax.swing.JComboBox();
        priceLabel = new javax.swing.JLabel();
        maxPrice = new javax.swing.JTextField();
        hotelsContainer2 = new javax.swing.JLayeredPane();
        selectLabel = new javax.swing.JLabel();
        onePers = new javax.swing.JComboBox();
        twoPers = new javax.swing.JComboBox();
        threePers = new javax.swing.JComboBox();
        fourPers = new javax.swing.JComboBox();
        onePersLabel = new javax.swing.JLabel();
        twoPersLabel = new javax.swing.JLabel();
        threePersLabel = new javax.swing.JLabel();
        fourPersLabel = new javax.swing.JLabel();
        dayToursPanel = new javax.swing.JPanel();
        dayToursLabel = new javax.swing.JLabel();
        contButton3 = new javax.swing.JButton();
        flightPanel = new javax.swing.JPanel();
        flightLabel = new javax.swing.JLabel();
        contButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        bookPanel.setBackground(new java.awt.Color(255, 255, 255));

        SearchQ.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        SearchQ.setText("What would you like to search for?");

        contButton1.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        contButton1.setText("Continue");
        contButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButton1ActionPerformed(evt);
            }
        });

        FlightCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightCheckboxActionPerformed(evt);
            }
        });

        HotelCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelCheckboxActionPerformed(evt);
            }
        });

        DayToursCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayToursCheckboxActionPerformed(evt);
            }
        });

        Flights.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        Flights.setText("Flights");

        Hotels.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        Hotels.setText("Hotels");

        DayTours.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        DayTours.setText("Day Tours");

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Flights)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookPanelLayout.createSequentialGroup()
                                .addComponent(FlightCheckbox)
                                .addGap(29, 29, 29)))
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(Hotels))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(HotelCheckbox)))
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(DayTours))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(DayToursCheckbox))))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(contButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(SearchQ)))
                .addContainerGap(831, Short.MAX_VALUE))
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(SearchQ)
                .addGap(56, 56, 56)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Flights, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hotels, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DayTours, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FlightCheckbox)
                        .addComponent(HotelCheckbox))
                    .addComponent(DayToursCheckbox))
                .addGap(69, 69, 69)
                .addComponent(contButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        mainPanel.add(bookPanel, "card12");

        hotelPanel.setBackground(new java.awt.Color(255, 255, 255));

        hotelLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        hotelLabel.setText("Hotels");

        contButton2.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        contButton2.setText("Continue");
        contButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					contButton2ActionPerformed(evt);
				} catch (NumberFormatException | ParseException | IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        backButton1.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        backButton1.setText("Back");
        backButton1.setMaximumSize(new java.awt.Dimension(137, 41));
        backButton1.setMinimumSize(new java.awt.Dimension(137, 41));
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        hotelsContainer1.setLayout(new java.awt.GridLayout(0, 2, 10, 15));

        arrivalDateLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        arrivalDateLabel.setText("Arrival date (yyyymmdd)");
        hotelsContainer1.add(arrivalDateLabel);
        hotelsContainer1.add(arrivalDate);

        nightsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        nightsLabel.setText("Number of nights");
        nightsLabel.setToolTipText("");
        hotelsContainer1.add(nightsLabel);

        nights.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", " ", " " }));
        nights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightsActionPerformed(evt);
            }
        });
        hotelsContainer1.add(nights);

        locationLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        locationLabel.setText("Hotel location");
        hotelsContainer1.add(locationLabel);

        hotelLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelLocationActionPerformed(evt);
            }
        });
        hotelsContainer1.add(hotelLocation);

        hotelNameLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        hotelNameLabel.setText("Hotel name");
        hotelsContainer1.add(hotelNameLabel);
        hotelsContainer1.add(hotelName);

        starsLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        starsLabel.setText("Minimum stars");
        hotelsContainer1.add(starsLabel);

        stars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "1", "2", "3", "4", "5" }));
        hotelsContainer1.add(stars);

        priceLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        priceLabel.setText("Maximum price");
        priceLabel.setMaximumSize(new java.awt.Dimension(119, 19));
        priceLabel.setMinimumSize(new java.awt.Dimension(119, 19));
        priceLabel.setPreferredSize(new java.awt.Dimension(119, 19));
        hotelsContainer1.add(priceLabel);

        maxPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxPriceActionPerformed(evt);
            }
        });
        hotelsContainer1.add(maxPrice);

        selectLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        selectLabel.setText("Please select the number of rooms of each type you wish to book:");

        onePers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        twoPers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));

        threePers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        fourPers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        onePersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        onePersLabel.setText("1 pers");

        twoPersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        twoPersLabel.setText("2 pers");

        threePersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        threePersLabel.setText("3 pers");

        fourPersLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        fourPersLabel.setText("4 pers");

        javax.swing.GroupLayout hotelsContainer2Layout = new javax.swing.GroupLayout(hotelsContainer2);
        hotelsContainer2.setLayout(hotelsContainer2Layout);
        hotelsContainer2Layout.setHorizontalGroup(
            hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelsContainer2Layout.createSequentialGroup()
                .addComponent(selectLabel)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelsContainer2Layout.createSequentialGroup()
                .addComponent(onePersLabel)
                .addGap(18, 18, 18)
                .addComponent(onePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(twoPersLabel)
                .addGap(18, 18, 18)
                .addComponent(threePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(threePersLabel)
                .addGap(18, 18, 18)
                .addComponent(twoPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fourPersLabel)
                .addGap(18, 18, 18)
                .addComponent(fourPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        hotelsContainer2Layout.setVerticalGroup(
            hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelsContainer2Layout.createSequentialGroup()
                .addComponent(selectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(hotelsContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onePersLabel)
                    .addComponent(twoPersLabel)
                    .addComponent(threePersLabel)
                    .addComponent(fourPersLabel))
                .addGap(25, 25, 25))
        );
        hotelsContainer2.setLayer(selectLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(onePers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(twoPers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(threePers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(fourPers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(onePersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(twoPersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(threePersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hotelsContainer2.setLayer(fourPersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout hotelPanelLayout = new javax.swing.GroupLayout(hotelPanel);
        hotelPanel.setLayout(hotelPanelLayout);
        hotelPanelLayout.setHorizontalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1159, Short.MAX_VALUE)
                .addComponent(contButton2)
                .addGap(68, 68, 68))
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(hotelLabel))
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hotelsContainer1)
                            .addComponent(hotelsContainer2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hotelPanelLayout.setVerticalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelLabel)
                .addGap(40, 40, 40)
                .addComponent(hotelsContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hotelsContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        mainPanel.add(hotelPanel, "card11");

        dayToursPanel.setBackground(new java.awt.Color(255, 255, 255));

        dayToursLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        dayToursLabel.setText(" DayTours");

        contButton3.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        contButton3.setText("Continue");

        javax.swing.GroupLayout dayToursPanelLayout = new javax.swing.GroupLayout(dayToursPanel);
        dayToursPanel.setLayout(dayToursPanelLayout);
        dayToursPanelLayout.setHorizontalGroup(
            dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayToursPanelLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addGroup(dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dayToursLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap(1090, Short.MAX_VALUE))
        );
        dayToursPanelLayout.setVerticalGroup(
            dayToursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayToursPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(dayToursLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(contButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        mainPanel.add(dayToursPanel, "card12");

        flightPanel.setBackground(new java.awt.Color(255, 255, 255));

        flightLabel.setText("Flight stuff");

        contButton4.setText("Continue");
        contButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout flightPanelLayout = new javax.swing.GroupLayout(flightPanel);
        flightPanel.setLayout(flightPanelLayout);
        flightPanelLayout.setHorizontalGroup(
            flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightPanelLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addGroup(flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contButton4)
                    .addComponent(flightLabel))
                .addContainerGap(1151, Short.MAX_VALUE))
        );
        flightPanelLayout.setVerticalGroup(
            flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(flightLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(contButton4)
                .addGap(87, 87, 87))
        );

        mainPanel.add(flightPanel, "card10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButton1ActionPerformed
        
        if(FlightCheckbox.isSelected()){
           flightPanel.setVisible(true);
           bookPanel.setVisible(false);
        }
        else if (HotelCheckbox.isSelected()){
            hotelPanel.setVisible(true);
            bookPanel.setVisible(false);
        }
        else if (DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            bookPanel.setVisible(false);
            
        }
        
        
        
    }//GEN-LAST:event_contButton1ActionPerformed

    private void DayToursCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayToursCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayToursCheckboxActionPerformed

    private void FlightCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightCheckboxActionPerformed

    private void HotelCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotelCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HotelCheckboxActionPerformed

    private void contButton2ActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, ParseException, IOException {//GEN-FIRST:event_contButton2ActionPerformed
        if (DayToursCheckbox.isSelected()){
            dayToursPanel.setVisible(true);
            hotelPanel.setVisible(false);
            
        }        
        PlaceHolder();
    }//GEN-LAST:event_contButton2ActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        if(FlightCheckbox.isSelected()){
            flightPanel.setVisible(true);
            hotelPanel.setVisible(false);
            
        }
        
        
    }//GEN-LAST:event_backButton1ActionPerformed

    private void contButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButton4ActionPerformed
        
        if(HotelCheckbox.isSelected()){
            hotelPanel.setVisible(true);
            flightPanel.setVisible(false);
            
            
        }
        
    }//GEN-LAST:event_contButton4ActionPerformed

    private void nightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nightsActionPerformed

    private void hotelLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelLocationActionPerformed

    private void maxPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxPriceActionPerformed

   

    
    public void PlaceHolder() throws NumberFormatException, ParseException, IOException {
    	int[] arr = new int[4];
    	arr[0] = onePers.getSelectedIndex();
    	arr[1] = twoPers.getSelectedIndex();
    	arr[2] = threePers.getSelectedIndex();
    	arr[3] = fourPers.getSelectedIndex();
    	if (maxPrice.getText().isEmpty()) {
    		maxPrice.setText("-1");
    	}
    	logic.HotelSearch(hotelLocation.getText(), arrivalDate.getText(), hotelName.getText(), nights.getSelectedIndex(), stars.getSelectedIndex(), Integer.parseInt(maxPrice.getText()), arr);
    	logic.DisplayHotelResults();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DayTours;
    private javax.swing.JCheckBox DayToursCheckbox;
    private javax.swing.JCheckBox FlightCheckbox;
    private javax.swing.JLabel Flights;
    private javax.swing.JCheckBox HotelCheckbox;
    private javax.swing.JLabel Hotels;
    private javax.swing.JLabel SearchQ;
    private javax.swing.JTextField arrivalDate;
    private javax.swing.JLabel arrivalDateLabel;
    private javax.swing.JButton backButton1;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JButton contButton1;
    private javax.swing.JButton contButton2;
    private javax.swing.JButton contButton3;
    private javax.swing.JButton contButton4;
    private javax.swing.JLabel dayToursLabel;
    private javax.swing.JPanel dayToursPanel;
    private javax.swing.JLabel flightLabel;
    private javax.swing.JPanel flightPanel;
    private javax.swing.JComboBox fourPers;
    private javax.swing.JLabel fourPersLabel;
    private javax.swing.JLabel hotelLabel;
    private javax.swing.JTextField hotelLocation;
    private javax.swing.JTextField hotelName;
    private javax.swing.JLabel hotelNameLabel;
    private javax.swing.JPanel hotelPanel;
    private javax.swing.JLayeredPane hotelsContainer1;
    private javax.swing.JLayeredPane hotelsContainer2;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField maxPrice;
    private javax.swing.JComboBox nights;
    private javax.swing.JLabel nightsLabel;
    private javax.swing.JComboBox onePers;
    private javax.swing.JLabel onePersLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JComboBox stars;
    private javax.swing.JLabel starsLabel;
    private javax.swing.JComboBox threePers;
    private javax.swing.JLabel threePersLabel;
    private javax.swing.JComboBox twoPers;
    private javax.swing.JLabel twoPersLabel;
    // End of variables declaration//GEN-END:variables
}